---
- hosts: localhost
  connection: local

  tasks:
    - name: Install main packages
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - bash-completion
        - "@base-x"
        - awesome
        - dbus-x11
        - flatpak
        - vim
        - htop
        - glibc-langpack-ru
        - flameshot
        - tar
        - tree
      register: packages
      become: yes

    - name: Add .Xclient
      template:
        src: files/.Xclient
        dest: "/home/{{ user }}/.Xclient"

    - name: Ensures .config/awesome dir exists
      file:
        path: "/home/{{ user }}/.config/awesome"
        state: directory

    - name: Copy awesome config
      copy:
        src: /etc/xdg/awesome/rc.lua
        dest: "/home/{{ user }}/.config/awesome/rc.lua"
      when: not ansible_check_mode

    - name: Xorg autostart setting
      lineinfile:
        dest: "/home/{{ user }}/.bash_profile"
        line: "[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx"
