---
- hosts: localhost
  connection: local

  tasks:
    - name: Install main packages
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - bash-completion
        - "@base-x"
        - awesome
        - dbus-x11
        - flatpak
        - vim
        - htop
        - glibc-langpack-ru
        - flameshot
        - tar
        - tree
      register: packages
      become: yes
      tags: base

    - name: Xorg
      include_tasks: tasks/xorg.yml
      tags: [base, xorg]

    - name: Awesome WM
      include_tasks: tasks/awesome.yml
      tags: [base, awesome]

    - name: Kitty Terminal
      include_tasks: tasks/kitty.yml
      tags: kitty