---
- hosts: localhost
  connection: local
  vars:
    user: "{{ ansible_user_id }}"

  roles:
    - role: awesome
      tags: [awesome, minimal]

    - role: flatpak
      tags: [flatpak, mimimal]

    - role: system
      tags: [system, minimal]

    - role: kitty
      tags: [kitty]

    - role: picom
      tags: [picom]

    - role: vscode
      tags: [vscode]

    - role: rofi
      tags: [rofi]

  tasks:
    - name: Install additional packages
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - bash-completion
        - vim
        - htop
        - glibc-langpack-ru
        - flameshot
        - tar
        - tree
        - keepassxc
        - rclone
        - openssl
        - cryptsetup
        - light
        - arandr
        - openconnect
        - acpi
        - ImageMagick
        - ffmpeg
        - xclip
        - pwgen
      become: true
      tags: [minimal]