---
- hosts: localhost
  connection: local

  roles:
    - role: awesome
      tags: [awesome, minimal]

    - role: flatpak
      tags: [flatpak, mimimal]

    - role: kitty
      tags: [kitty]

    - role: picom
      tags: [picom]

  tasks:
    - name: Install additional packages
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - bash-completion
        - vim
        - htop
        - glibc-langpack-ru
        - flameshot
        - tar
        - tree
        - chromium
        - keepassxc
        - rclone
      become: true
      tags: [minimal]