---
- hosts: localhost
  connection: local
  vars:
    user: "{{ ansible_user_id }}"

  pre_tasks:
    - name: Install required packages
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - rsync
        - unzip
        - alsa-utils
        - bind-utils
        - xss-lock
        - light
        - acpi
        - cronie
      become: true
      tags: [minimal]

  roles:
    - role: awesome-xorg
      tags: [awesome, minimal]

    - role: flatpak
      tags: [flatpak, mimimal]

    - role: system
      tags: [system, minimal]

    - role: kitty
      tags: [kitty]

    - role: picom
      tags: [picom]

    - role: vscode
      tags: [vscode]

    - role: rofi
      tags: [rofi]

    - role: i3lock-color
      tags: [i3lock-color]

    - role: ranger
      tags: [ranger]

  tasks:
    - name: Install additional packages
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - bash-completion
        - vim
        - htop
        - wget
        - glibc-langpack-ru
        - flameshot
        - tar
        - tree
        - keepassxc
        - rclone
        - openssl
        - cryptsetup
        - arandr
        - openconnect
        - ImageMagick
        - ffmpeg
        - xclip
        - pwgen
        - vlc
        - libvdpau-va-gl # mplayer
        - kernel-tools   # cpupower
        - thunar
        - shotwell
      become: true
      tags: [minimal]
