---
- name: Xorg
  block:
  - name: Add .Xclients
    template:
      src: files/.Xclients
      dest: "/home/{{ user }}/.Xclients"
      mode: u=rwx,g=r,o=r

  - name: Xorg autostart setting
    lineinfile:
      dest: "/home/{{ user }}/.bash_profile"
      line: "[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx"