---
- name: Import key
  command: rpm --import https://packages.microsoft.com/keys/microsoft.asc
  become: true

- name: Add config
  copy:
    src: files/vscode.repo
    dest: /etc/yum.repos.d/vscode.repo
  become: true

- name: Check update
  dnf:
    update_cache: true

- name: Install
  dnf:
    name: code
    state: present
  become: true

- stat: path="{{ vscode_user_config_dir }}"
  register: dir_vscode_user

- name: Create dir - {{ vscode_user_config_dir }}
  file:
    path: "{{ vscode_user_config_dir }}"
    state: directory
  when: not dir_vscode_user.stat.exists

- name: Copy config
  template:
    src: files/settings.json
    dest: "{{ vscode_user_config_dir }}/settings.json"