---
- name: Import key
  command: rpm --import https://packages.microsoft.com/keys/microsoft.asc
  become: true

- name: Add config
  copy:
    src: files/vscode.repo
    dest: /etc/yum.repos.d/vscode.repo
  become: true

- name: Check update
  dnf:
    update_cache: true

- name: Install
  dnf:
    name: code
    state: present
  become: true

- name: Ensure {{ vscode_user_config_dir }} dir exist
  file:
    path: "{{ vscode_user_config_dir }}"
    state: directory

- name: Copy config
  template:
    src: files/settings.json
    dest: "{{ vscode_user_config_dir }}/settings.json"