---
- name: Bash setup
  block:
    - name: Copy global bashrc
      template:
        src: files/bashrc
        dest: /etc/bashrc
      become: true

    - name: Copy user .bashrc
      template:
        src: files/.bashrc
        dest: "/home/{{ user }}/.bashrc"

    - name: Ensure {{ bashrc_dir }} dir exist
      file:
        path: "{{ bashrc_dir }}"
        state: directory

    - name: Copy aliases
      template:
        src: files/.bashrc.d/bash_aliases
        dest: "{{ bashrc_dir }}/bash_aliases"
  tags: [bash]

- name: Enable rpmfusion
  dnf:
    name:
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"
    state: present
    disable_gpg_check: true
  become: true

- name: Keychrone fix
  ansible.builtin.cron:
    name: "Keychrone fix"
    job: "echo 0 > /sys/module/hid_apple/parameters/fnmode"
  become: true

- name: Setup monitor hotplug
  block:
    - name: Ensure {{ monitor_layout_script_dir }} dir exist
      file:
        path: "{{ monitor_layout_script_dir }}"
        state: directory

    - name: Copy layout script
      template:
        src: files/default_layout.sh
        dest: "{{ monitor_layout_script_dir }}/"
        mode: '744'

    - name: Copy udev rule
      template:
        src: files/98-monitor-hotplug.rules
        dest: /etc/udev/rules.d/
      become: true
      notify: reload udev
  tags: [monitor-hotplug]

- name: Install fonts
  block:
    - name: Ensure {{ fonts_dir }} dir exist
      file:
        path: "{{ fonts_dir }}"
        state: directory

    - name: Ensure font dirs exist
      file:
        path: "{{ fonts_dir }}/{{ item }}"
        state: directory
      loop:
        - JetBrainsMono

    - name: Download JetbrainsMono Font
      unarchive:
        src: "https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip"
        dest: "{{ fonts_dir }}/JetBrainsMono"
        remote_src: yes
      when: not ansible_check_mode

    - name: Update font cache
      command: "fc-cache -fv {{ fonts_dir }}" # fc-list
  tags: [fonts]

- name: Enable dark theme
  block:
    - name: Set Adwaita-dark
      command: gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-Dark'

    - name: Set prefer-dark
      command: gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

- name: Copy mimeapps.list
  template:
    src: files/mimeapps.list
    dest: "/home/{{ user }}/.config/mimeapps.list"

- name: DNS
  block:
    - name: Disable systemd-resolved
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: false
      become: true

    - name: Copy resolv.conf
      template:
        src: files/resolv.conf
        dest: /etc/
      become: true
  tags: [dns]