---
- name: Install flatpak
  dnf:
    name: 
      - dbus-x11
      - flatpak
    state: present
  become: true

- name: Add the flathub flatpak repository remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install the packages
  community.general.flatpak:
    name: org.gnome.gedit
    state: present
  loop: "{{ default_flatpak_packages | list + flatpak_packages | default([]) }}"
