---
- name: Install dependencies
  dnf:
    name: 
      - dbus-devel 
      - gcc 
      - libconfig-devel
      - libdrm-devel
      - libev-devel
      - libX11-devel
      - libX11-xcb
      - libXext-devel
      - libxcb-devel
      - mesa-libGL-devel
      - meson
      - pcre-devel
      - pixman-devel
      - uthash-devel
      - xcb-util-image-devel
      - xcb-util-renderutil-devel
      - xcb-util-cursor-devel
      - xcb-util-devel
      - xcb-util-keysyms-devel
      - xcb-util-wm-devel
      - xcb-util-xrm-devel
      - xorg-x11-proto-devel
      - mesa-libEGL-devel
      - pcre2-devel
    state: present
  become: true

- name: Check if picom is installed
  stat:
    path: /usr/local/bin/picom
  register: picom_binary

- name: Install picom
  block:
  - name: Clone a repo - {{ picom_repository }}
    ansible.builtin.git:
      repo: "{{ picom_repository }}"
      dest: /tmp/picom

  - name: Build
    shell: meson --buildtype=release . build && ninja -C build
    args:
      chdir: /tmp/picom
    when: not ansible_check_mode

  - name: Add binary to /usr/local/bin/
    command: ninja -C build install
    args:
      chdir: /tmp/picom
    become: true
    when: not ansible_check_mode
  when: not picom_binary.stat.exists

- name: Ensure {{ picom_config_dir }} dir exist
  file:
    path: "{{ picom_config_dir }}"
    state: directory

- name: Copy default config
  template:
    src: files/picom.conf
    dest: "{{ picom_config_dir }}/picom.conf"
