---
- name: Install
  dnf:
    name: kitty
    state: present
  become: true

- name: Ensure {{ kitty_config_dir }} dir exist
  file:
    path: "{{ kitty_config_dir }}"
    state: directory

- name: Add config
  copy:
    src: files/kitty.conf
    dest: "{{ kitty_config_dir }}/kitty.conf"