---
- name: Install dependencies
  dnf:
    name: 
      - xset
      - autoconf
      - automake
      - cairo-devel
      - fontconfig
      - gcc
      - libev-devel
      - libjpeg-turbo-devel
      - libXinerama
      - libxkbcommon-devel
      - libxkbcommon-x11-devel
      - libXrandr
      - pam-devel
      - pkgconf
      - xcb-util-image-devel
      - xcb-util-xrm-devel
    state: present
  become: true

- name: Install i3lock-color
  block:
  - name: Clone a repo - https://github.com/Raymo111/i3lock-color
    ansible.builtin.git:
      repo: https://github.com/Raymo111/i3lock-color
      dest: /tmp/i3lock-color

  - name: Build and Install i3lock-color
    command: ./install-i3lock-color.sh
    args:
      chdir: /tmp/i3lock-color
      creates: /usr/bin/i3lock

- name: Install
  shell: wget https://raw.githubusercontent.com/betterlockscreen/betterlockscreen/main/install.sh -O - -q | bash -s user
  args:
    creates: "/home/{{ user }}/.local/bin/betterlockscreen"

- name: Ensure .config dir exist
  file:
    path: "/home/{{ user }}/.config"
    state: directory

- name: Copy config
  template:
    src: files/betterlockscreenrc
    dest: "/home/{{ user }}/.config/"