---
- name: Install
  dnf:
    name: rofi
    state: present
  become: true

- name: Ensure {{ rofi_config_dir }} dir exist
  file:
    path: "{{ rofi_config_dir }}"
    state: directory

- name: Add config
  copy:
    src: "files/{{ item }}"
    dest: "{{ rofi_config_dir }}/{{ item }}"
  loop:
    - config.rasi
    - theme.rasi