---
- name: Install
  dnf:
    name: rofi
    state: present
  become: true

- stat: path="{{ rofi_config_dir }}"
  register: dir_rofi

- name: Create dir - {{ rofi_config_dir }}
  file:
    path: "{{ rofi_config_dir }}"
    state: directory
  when: not dir_rofi.stat.exists

- name: Add config
  copy:
    src: "files/{{ item }}"
    dest: "{{ rofi_config_dir }}/{{ item }}"
  loop:
    - config.rasi
    - theme.rasi
  when: not (ansible_check_mode and not dir_kitty.stat.exists)
