---
- name: Setup Xorg
  block:
  - name: Install Xorg
    dnf:
      name: "@base-x"
      state: present
    become: true

  - name: Add .Xclients
    template:
      src: files/.Xclients
      dest: "/home/{{ user }}/.Xclients"
      mode: u=rwx,g=r,o=r

  - name: Xorg autostart setting
    lineinfile:
      dest: "/home/{{ user }}/.bash_profile"
      line: "[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx"
  tags: xorg

- name: Install
  dnf:
    name: awesome
    state: present
  become: true

- stat: path="{{ awesome_config_dir }}"
  register: dir_awesome

- name: Create dir - {{ awesome_config_dir }}
  file:
    path: "{{ awesome_config_dir }}"
    state: directory
  when: not dir_awesome.stat.exists

- name: Copy default config
  copy:
    src: /etc/xdg/awesome/rc.lua
    dest: "{{ awesome_config_dir }}/rc.lua"
  when: not (ansible_check_mode and not dir_awesome.stat.exists)