---
- name: Setup Xorg
  block:
  - name: Install Xorg
    dnf:
      name: "@base-x"
      state: present
    become: true

  - name: Add .Xclients
    template:
      src: files/.Xclients
      dest: "/home/{{ user }}/.Xclients"
      mode: u=rwx,g=r,o=r

  - name: Xorg autostart setting
    lineinfile:
      dest: "/home/{{ user }}/.bash_profile"
      line: "[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx"
  tags: xorg

- name: Install
  dnf:
    name: awesome
    state: present
  become: true

- name: Ensure {{ awesome_config_dir }} dir exist
  file:
    path: "{{ awesome_config_dir }}"
    state: directory

- name: Copy themes
  synchronize:
    src: files/themes
    dest: "{{ awesome_config_dir }}/"

- name: Copy icons
  synchronize:
    src: files/icons/Adwaita
    dest: /usr/share/icons/
  become: true

- name: Copy config
  template:
    src: files/rc.lua
    dest: "{{ awesome_config_dir }}/rc.lua"

- name: Add widgets repo
  ansible.builtin.git:
    repo: https://github.com/nserd/awesome-wm-widgets.git
    dest: "{{ awesome_config_dir }}/awesome-wm-widgets"